version: "2"
services:
# jQuery Front End
  autocomplete-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: "autocomplete-app"
    restart: always
    environment:
      - APIHOST=localhost:5000
    ports:
      - "80:80"
    hostname: autocomplete-app
