apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: autocomplete-app
  name: autocomplete-app
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: autocomplete-app
    spec:
      containers:
      - env:
        - name: API_HOST
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: API_HOST
        image: mayankt/autocomplete-app:latest
        imagePullPolicy: Always
        name: autocomplete-app
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
