apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: autocomplete-app
  name: autocomplete-app
spec:
  ports:
  - name: "app"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: autocomplete-app
  type: LoadBalancer
status:
  loadBalancer: {}
